### ISSUE TITLE
Automatically closing issues after a pull request merge

### ISSUE THREAD

**Issue by MarcvdSluys** [robvanderleek/create-issue-branch#137]
First of all, thank you for the new feature to auto-close issues on PR merge, it sounds very useful!

I have a question about the configuration.  I originally installed your app on my account using [Option 1](https://github.com/robvanderleek/create-issue-branch#option-1-install-the-github-app).  Your instruction to use the new feature is to update the configuration YAML, which was so far only necessary for [Option 2](https://github.com/robvanderleek/create-issue-branch#option-2-configure-github-action).  So my question is, do I have to switch from Option 1 to Option 2 to use the new feature, or should it just work?

**Comment by robvanderleek** [comment]
Hi @MarcvdSluys 👋 

No, you don't need to switch to option 2.
There are two kind of YAML files: 1 is the configuration file for the app itself and the other is the GitHub Actions workflow file. 
If you're using option 1 you don't need the second YAML. But if you want to enable some optional features you do need the first YAML.

To test the auto close issue feature, create this YAML file in the repo: `.github/issue-branch.yml`, with the following contents:

```yaml
autoCloseIssue: true
```

There are more configuration options you can put in this file, see [here](https://github.com/robvanderleek/create-issue-branch#configuration).

You can also have a single YAML file that configures the app for all your repos. For that you need to create a repo called `.github` (yes, the repo is called `.github`) and then put the configuration YAML there (again in the location `.github/issue-branch.yml`)

Let me know if this works for you 😄

**Comment by MarcvdSluys** [comment]
Wow, this is so cool, and it works!

Thank you so much for taking the time to explain GitHub config/YAML to a newbie!  I find it quite hard to find for clear info on this topic - only slightly better than googling for GitHub and Issue, which matches every GH repo... If you happen to have a good link to GH config/YAML documentation, where the .github/.github/file.yaml and all basics are explained, that would be much appreciated.  But in any case, I'll close this "issue"  :-)

**Comment by robvanderleek** [comment]
GitHub Probot apps (i.e. the apps you find here: https://probot.github.io/) load their YAML configuration files from a directory called `.github`
There is some developer documentation about this (https://probot.github.io/docs/best-practices/#configuration) but I don't know of any general user documentation.

The `.github` directory is also used to store GitHub Actions workflows, for example to automate your CI/CD pipeline. If you are not familiar with GitHub Actions (or CI/CD) I would highly recommend reading the documentation for that here: https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
