### ISSUE TITLE
Removing the request comments

### ISSUE THREAD

**Issue by movsar** [robvanderleek/create-issue-branch#145]
Great app, thank you for creating it!

I'd love if you would make it auto remove the request "/cib" comment after the successful creation of a new branch, it would be so nice and neat!

**Comment by robvanderleek** [comment]
Thanks for the compliment! 😄 

I'd rather not delete entries from the comment timeline, they can be valuable for traceability purposes. Do you know of any GH Apps that do this? Let me know if this is common practice. Closing this issue for now.
