### ISSUE TITLE
Creating a branch when one already exists

### ISSUE THREAD

**Issue by movsar** [robvanderleek/create-issue-branch#146]
Sometimes you need to create multiple branches for the same issue, for instance when you merged one, but later realize you need to do something different related to the issue etc

Currently if we do `/cib` for the second time it responds the 

> branch already exists

It would be more functional if the app could add an iterator to the name and create a new branch anyways, like:

> issue-2
> issue-2-1, etc

Thank you

**Comment by robvanderleek** [comment]
Hi @movsar 😄 

I think you can use the existing branch to continue work on the issue? (perhaps pull in changes from master first)
Personally I enable the [delete branch on merge feature](https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches) for my repos. When more work for the same issue needs to happen after a merge `/cib` will create a fresh branch from master.

KR, Rob
