### ISSUE TITLE
Close issue with custom branchName after PR merge

### ISSUE THREAD

**Issue by jllodra** [robvanderleek/create-issue-branch#149]
The autoclose issue after PR merge is awesome,
but according to the doc I cannot use it because I use a custom branchName pattern:

```yml
branchName: 'issue/${issue.number}-${issue.title}'
```

Is there any workaround for me?
Would it be possible to implement that autoclose issue would honor the branchName setting?

Thank you

EDIT:

Just read the code and I think it would work with my branchName pattern:
https://github.com/robvanderleek/create-issue-branch/blob/master/src/github.js#L41

**Comment by robvanderleek** [comment]
Hi @jllodra 

Sorry for the delayed reply, and thanks for your feedback.

Great you've been able to use the source to figure this out.
Does the autoclose issue functionality now works for your use-case? If so, let me know and I'll update the documentation 😉

Rob

**Comment by jllodra** [comment]
Hi @robvanderleek,

Yes, it works, code looks for a number after the last / in the branch name.
Thank you for asking.
