### ISSUE TITLE
Config: Choose branch to branch from 

### ISSUE THREAD

**Issue by adam-nygate** [robvanderleek/create-issue-branch#155]
Currently, it looks like the default repository branch is used to branch from. Is there any way that this can be made customisable?

**Comment by robvanderleek** [comment]
Hi @adam-nygate 

Currently it's only possible to select a different source branch based on an issue label [1].
The default repository branch is indeed taken as the source branch in all other cases.
Would the setup described in [1] work for you? Can you describe your development process a bit?

[1] https://github.com/robvanderleek/create-issue-branch#branch-name-prefix-based-on-issue-label

**Comment by maxarndt** [comment]
Hey @robvanderleek!

This would be a super handy feature for me as well!

I'm using your app in chatops mode. This is my use case:

Let me say I'm working on `issue A` and at a certain point you stumble across another problem which is from now on tracked in `issue B`. 
`Issue B` can neither be implemented before merging `issue A` into your default branch nor can `Issue B` be implemented after merging `issue A`. So `issue B` needs to be merged together with `issue A` into the default branch.

This can be done by addressing the necessary changes in a fresh branch for `issue B`, which is branched from the `issue A`-Branch and merged back to it as soon the work on `issue B` is finished.

So at the beginning I would have called `/cib` to create a branch for `issue A`. After creating `issue B` I would need to call `/cib --from issue-A-some-issue-title`.

What do you think about this use case?

---
As a little hint:
In your answer above you linked the wrong heading in your readme. I guess you wanted to link the `#source-branch-based-on-issue-label` section.

**Comment by robvanderleek** [comment]
Hi @maxarndt 😄 

Apologies for my late reply.

You are right about the link, corrected that, thanks.

Your use-case is clear, I must admit that I sometimes branch from an issue-branch, although I really try to avoid it.
I've put your request on the [features under consideration list](https://github.com/robvanderleek/create-issue-branch#features-under-consideration) as I don't have time to implement it at the moment. I'm also not sure if making the ChatOps command more advanced is the way foward but maybe GitHub [autolinked references](https://docs.github.com/en/github/writing-on-github/autolinked-references-and-urls#issues-and-pull-requests) would make it intuitive to do something like `/cib #155`.

Thanks a lot for your feedback, hope this is not a major blocker for you.
