### ISSUE TITLE
documentation: token

### ISSUE THREAD

**Issue by Isanderthul** [robvanderleek/create-issue-branch#160]
Please can you explain the permissions required when creating a token for ```GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}```

**Comment by Isanderthul** [comment]
I wanted to create branches, so I found this action via google, and I have not used github actions before, so a bit of background and more explaining about how to do it would be great. I did not want to use the forst option because I only want to apply this to one repo.

**Comment by robvanderleek** [comment]
Hi @Isanderthul 😄 

The `secrets.GITHUB_TOKEN` will be supplied by GitHub automatically when running an action. You do not need to create this token yourself, the permissions of this token are limited to the repository for which the action runs.

Please note that when you [install it as an App](https://github.com/apps/create-issue-branch) (i.s.o. Action) you can select the repositories for which you want `create-issue-branch` to be installed:

![image](https://user-images.githubusercontent.com/5324924/83942774-f99f9500-a7f6-11ea-9082-0e87fd7ef457.png)
 
Let me know if this helps,
Rob
