### ISSUE TITLE
Feature Request: Support .yaml or .yml extension for issue-branch.yml

### ISSUE THREAD

**Issue by andrewcole** [robvanderleek/create-issue-branch#169]
Github Actions [supports either .yml or .yaml](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#creating-a-workflow-file)) for it's actions files, and I just spent way too long trying to figure out why https://github.com/illallangi/.github/blob/master/.github/issue-branch.yaml wasn't working for me (since renamed to .yml).

I'll have a go at implementing this and will create a pull request.

**Comment by robvanderleek** [comment]
Hi @andrewcole

Ouch, I know how frustrating this can be. 
I was not aware GitHub Actions supports both `.yml` and `.yaml`. I based this app on the [Probot](https://probot.github.io/docs/) JavaScript framework.
An obvious place to start your modifcations would be [config.js](https://github.com/robvanderleek/create-issue-branch/blob/master/src/config.js) (and `config.test.js`).

Thanks for the feedback and good luck with the PR!

**Comment by robvanderleek** [comment]
Hey @andrewcole 

Did you find any time to work on this?
Let me know if you need help 😄 Also let me know if you're too busy, maybe I can take a look myself.

Rob

**Comment by andrewcole** [comment]
Hey @robvanderleek, I started looking at this and quickly realised I was out of my depth, not having a lot of JS experience.

**Comment by andrewcole** [comment]
Looks easy when you do it! Thanks @robvanderleek!

**Comment by robvanderleek** [comment]
It's easy when you know where to look 😉 
The App has been deployed on Heroku.
Let me know if it still does not pick up `.yaml` files.
Thanks for the feedback!
