### ISSUE TITLE
Branch name customization

### ISSUE THREAD

**Issue by wilbertcaba** [robvanderleek/create-issue-branch#17]
Great job solving this problem! I wish there was a way to customize how these branch names are generated since some issues have a lengthy title and it could be a pain to work with a branch called `issue-13-Homepage_Testimonials_add_Google_and_Trip_Advisor_reviews` and so forth. 

For my specific case, something like `issue-13` or `i13` would be perfect.

Any thoughts?

**Comment by robvanderleek** [comment]
Hi @wilbertcaba, this is my first Github app but I think it's common to configure apps through a YAML file in the `.github` directory of the repo (https://probot.github.io/docs/best-practices/#store-configuration-in-the-repository).

Not sure what the default should be, currently I include the title as you mention. Would a simple `.github/issue-branch.yml` with `branchName: {tiny, short, full}` suffice? `full` would then remain the default.

**Comment by robvanderleek** [comment]
Hi @wilbertcaba, the branch name can now be configured, see https://github.com/apps/create-issue-branch
I'm closing this issue, thanks for reporting it.

**Comment by wilbertcaba** [comment]
Awesome! Keep up the good work! 🤙

**Comment by plumwd** [comment]
Whoo thank you! This will help our team immensely.
