### ISSUE TITLE
Feature Request: Force lowercase

### ISSUE THREAD

**Issue by Jamesking56** [robvanderleek/create-issue-branch#176]
It would be nice if we could force the branch name to always be lowercase

**Comment by robvanderleek** [comment]
Hi @Jamesking56 

Thanks for the feedback 😄 

It should be possible to extend the `${...}` placeholder substitution functionality in the [custom branch name](https://github.com/robvanderleek/create-issue-branch#branch-names) configuration option a bit to support this.

For example, I can adopt the [bash-style](https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion) parameter expansion flags `^`, and `,` to uppercase and lowercase strings (I don't think the options to uppercase or lowercase the first character are necessary).
If you want the issue title part of the branch to always be lowercase you would then configure it like this:

```yaml
branchName: '${issue.number}-${issue.title,}'
```

Would this work for your use-case?

**Comment by robvanderleek** [comment]
Hi @Jamesking56 

I've implemented the lowercase and uppercase operators for branch name placeholder substitutions. Hope this works for your use-case.
