### ISSUE TITLE
Feature Request: Allow label management on automatic close issues

### ISSUE THREAD

**Issue by nthomas20** [robvanderleek/create-issue-branch#177]
When `autoCloseIssue: true` is set in the config closing the issue on PR completion is so handy and helpful! To complete my workflow, I still have to manually make a label adjustment where I remove
* `Status:In-Progress`

and set

* `Status:Completed`

I would find it very helpful if I could list a set of labels in these two areas to remove (if applied), and set just prior to closing the issue.
It would be really neat if I could give a wildcard on removal labels as well so I could indicate to remove any `Status:*` labels that might be set.

**Comment by robvanderleek** [comment]
Hi @nthomas20 

Nice to get positive feedback on the `autoCloseIssue` feature, thanks!

I don't think I've ever seen the usage of status labels as you describe before, they are different from the GitHub project board columns right? There was a discussion on automatically moving issues on the project board in [this issue](https://github.com/robvanderleek/create-issue-branch/issues/142).

I'm not sure if this way of working with status labels is very common, or that most teams use the project board for this.

Let me know your thoughts.

**Comment by nthomas20** [comment]
I'm not sure how common it is either, but when we're looking at a reasonably sized list of issues the filter by "in progress" status is very handy, we can do all of that filtering in one place without having to navigate to the project board. AFAIK, I haven't found a way to apply label changes to issues as they move through the project board (automated or otherwise). Software devs aren't lazy, but repetitive manual tasks like this have a tendency to be lost over time.

This is an efficiency/assistance ask :)

**Comment by robvanderleek** [comment]
Hi @nthomas20 

I'm closing this issue but added it for future reference to [this list](https://github.com/robvanderleek/create-issue-branch#roadmap-features). 
I'm just not sure if issue label management functionality should be added to this App, also since the project board provides the overview of issues that are in "todo" or "doing" (although I must admit working with the project board feels a bit clumsy at times).

Rob
