### ISSUE TITLE
Feature Request: Suppress "Branch already exists"

### ISSUE THREAD

**Issue by nthomas20** [robvanderleek/create-issue-branch#184]
When adding additional assignees to an issue which triggers a create branch action, if the branch already exists it adds a comment about the branch already existing.

> Branch already exists

I would like to suppress that specific error comment message via repo configuration.

**Comment by robvanderleek** [comment]
Hi @nthomas20 

I think we can drop that comment altogether for the "assign issue" flow and only leave it in for the ChatOps (`/cib`) flow.
The App will then no longer complain if a branch already exists when (re-)assigning an issue.

What do you think?

Rob

**Comment by nthomas20** [comment]
That sounds great to me!

**Comment by robvanderleek** [comment]
Hi @nthomas20 
I've deployed a fix for this.
