### ISSUE TITLE
Allow to specify a custom branch name

### ISSUE THREAD

**Issue by LifeIsStrange** [robvanderleek/create-issue-branch#194]
This is a blocker for us.

**Comment by robvanderleek** [comment]
Hi @LifeIsStrange 

There is a [configuration option](https://github.com/robvanderleek/create-issue-branch#branch-names) to customise the format of branch names.

For example:

```yaml
branchName: 'foo-${issue.number}-bar-${issue.title}'
```

results in branches named like: foo-1-bar-Fix-nasty-bug

If this is not sufficient, can you then please elaborate what functionality you're missing for your use-case?

**Comment by LifeIsStrange** [comment]
I'm currently on vacations, I'll reopen if I find limitations.
Thanks!
