### ISSUE TITLE
Feature request: Dashes instead of underscores

### ISSUE THREAD

**Issue by Jamesking56** [robvanderleek/create-issue-branch#200]
If we have an issue with  a title containing multiple words separated by spaces, this app creates the branch with underscores instead of spaces.

It would be nice if we could configure the branch word separator to be dashes instead.

**Comment by robvanderleek** [comment]
Hi @Jamesking56 

I've implemented a configuration flag that allows you to configure the separator character, please see the [Readme](https://github.com/robvanderleek/create-issue-branch#change-replacement-for-illegal-characters-in-branch-title)

Hope this fits your use-case, let me know otherwise.
