### ISSUE TITLE
Branch source customization

### ISSUE THREAD

**Issue by ilyasmohamed** [robvanderleek/create-issue-branch#21]
I'm not at all sure if this is even possible but I think it would be great to see some some of functionality in which you can specify which branch the new issue branch uses as a source. This would be especially useful in cases where you wish to branch off from the dev branch for issues that are an enhancement/new feature.

**Comment by robvanderleek** [comment]
Hi @ilyasmohamed,

Thanks for your time.

Currently all issue branches branch off from the repo's default branch. How would you like to see this feature implemented? It's fairly easy to add a configuration option to override the default branch, but then that branch would be the target for _all_ issue branches. I guess something can also be done by encoding the target branch in the issue title or add a configuration option to map issue labels to branches.

Let me know what you think.

**Comment by ilyasmohamed** [comment]
I had an idea which was based mainly around settings source branches based off the issue label, but in any case there should always be a fallback available. In terms of the best syntax to achieve this i'm not totally sure. But sticking with the idea of a yml config which you have already implemented then I think something like this may be feasible:

```
labels:
    enhancement:
        source_branch: dev
    bug:
        source_branch: master
    
    .
    .
    .
```

I've haven't looked too much into what data applications like yours have access to but the above idea assumes that it can ask labels on issues. 

Issues with the described implementation include, but are not limited to:
1. Issues can have multiple labels, so what should happen if an issue has multiple lables which are mapped in the config file. (A simple solution might be to just use the first match)
2. Do applications have access to issue labels

**Comment by robvanderleek** [comment]
To answer 2. yes, the app has access to the issue labels. For example, I get this array of labels for #22 :
```
labels: [
    {
      "id": 1456956799,
      "node_id": "MDU6TGFiZWwxNDU2OTU2Nzk5",
      "url": "https://api.github.com/repos/robvanderleek/create-issue-branch/labels/bug",
      "name": "bug",
      "color": "d73a4a",
      "default": true
    },
    {
      "id": 1456956801,
      "node_id": "MDU6TGFiZWwxNDU2OTU2ODAx",
      "url": "https://api.github.com/repos/robvanderleek/create-issue-branch/labels/documentation",
      "name": "documentation",
      "color": "0075ca",
      "default": true
    },
    {
      "id": 1456956805,
      "node_id": "MDU6TGFiZWwxNDU2OTU2ODA1",
      "url": "https://api.github.com/repos/robvanderleek/create-issue-branch/labels/enhancement",
      "name": "enhancement",
      "color": "a2eeef",
      "default": true
    }
  ]
```
Ordering in this array appears to be alphabetically as I added the `documentation` label last.

To answer 1. We can let the ordering of the label-branch mapping in the YAML be decisive for the source branch priority.

For issues without a label: source branch will remain the repo's default branch.

It gets a bit more confusing when labels are removed or changed after the branch has been created. Would it be OK for your use-case when that is not supported by this app?

**Comment by ilyasmohamed** [comment]
Yes, that makes sense and seems like it would be perfect for my use-case. In regards to the point about when labels are removed, what issues did you foresee?

**Comment by robvanderleek** [comment]
I've implemented the behaviour in #23 
The configuration format is a bit different as discussed above, see the [Readme](https://github.com/robvanderleek/create-issue-branch/blob/issue-21-Branch-source-customization/README.md)

It's not live but you can install the CIB staging app on a repo to test the feature: https://github.com/apps/create-issue-branch-staging

Let me know what you think of it. Also if you have any comments on the PR (or would like to contribute yourself) let me know.

I foresee some usability quirks when an issue is created and assigned and labels are modified afterwards (the source of the branch will then of course not be updated by the app). But maybe that's not a big problem in practice.

Thanks again for your time.

**Comment by ilyasmohamed** [comment]
This looks great. I'll definitely be checking it out on the weekend. Thanks

**Comment by ilyasmohamed** [comment]
@robvanderleek Had another idea as part of this new feature as it's something I like to do in order to group together my branches. I think it would be immensely useful to specify a branch name prefix e.g.

`branches:
  - label: enhancement
    name: dev
    branch-prefix: feature/
  - label: bug
    name: master 
    branch-prefix: bugfix/`

The logic could do something like: if the branch-prefix is not present then don't use a prefix.

Let me know your thoughts

**Comment by robvanderleek** [comment]
Hi @ilyasmohamed 

Although I like to keep my own branch-naming schemes very simple, your suggestion could indeed be a very valuable feature for larger code bases that follow a GitFlow-based scheme.

I don't think it's hard to implement (although variable substitution always brings it own set of problems :-)). 
I'll give it a go in the current branch and get back to you if I need help (for sure to review the implementation).

Rob

**Comment by codemile** [comment]
Came here looking to see if this feature exists, and I'm happy to see you're working on.

For me, I would like the source match to match the assigned milestone for the issue. So if an issue is assigned to milestone `2.0.0` then it would source from branch `2.0.0`.

Is something like that possible?

Right now, I have to set my default branch to the milestone branch and that means visitors to the repo are seeing the README for that branch, but those features are not yet published to npm. So I have to tell them to switch to master to see the current README.

**Comment by robvanderleek** [comment]
Hi @codemile 
That shouldn't be too hard to implement.
I've never seen this branching scheme before, do you perhaps know of other projects that also use it?
Would you like to see this implemented as a global setting or based on issue labels (as discussed above)?
Please be aware that branches are only created when issues are assigned, so at that point the source branch can be based on an associated milestone but changing the milestone of an already assigned issue does not change the source branch.
Let me know your thoughts and thanks for your time.

**Comment by codemile** [comment]
You might be right. I was rethinking this, and maybe it's not the best approach because people can change the milestone or assign it first before it's assigned a milestone.

I have been using this plugin which forces users to assign a milestone to new issues. So I forgot that I was using it, and I use a milestone branch for feature development.

https://github.com/scholzj/milestone-check

So I have a milestone `2.0.0` and a matching `2.0.x` feature branch, and I make `2.0.x` my default branch and this creates the problem of it becoming the landing page for the repository.

I'm not completely satisfied with this approach. So I'm thinking of switching back to `master` as my default branch, and having master track new feature development. I started using a `2.0.x.` branch because I was doing some large refactoring.

**Comment by robvanderleek** [comment]
Using the functionality I'm implementing currently you could configure the `2.0.x` branch for new development issues that are labeled as `enhancement`:

```
branches:
  - label: enhancement
    name: 2.0.x
```

I think it's best to keep your default branch at `master` and have at most 1 long term development branch for major refactorings. Using a more elaborate branching scheme with milestone branches sounds complicated to me. 

Let me know your thoughts.

PS The intro to reactgular.com is amazing :-)

**Comment by codemile** [comment]
This will work perfectly for milestones, and I switched back to master as my default. That seems to be working out.

Thanks for the compliment. The source code is on the repo if you want to make your own version of the website :)
