### ISSUE TITLE
Feature request: "Linked issues" for PRs

### ISSUE THREAD

**Issue by kartalerkoc** [robvanderleek/create-issue-branch#212]
Thank you for such a useful library! Right now, the issues are automatically being closed when a PR is merged since there is already connected information regarding issue and related branch.

The only problem is that issues are not linked inside PRs, so a related PR cannot be traced from within the issue. At this point, while merging the PR, would it be possible to add an automation to link the issue as well as closing the issue?

**Comment by robvanderleek** [comment]
Hi @kartalerkoc 

Thanks for the compliment 😄 

GitHub introduced this nice feature in the UI to link issues and PRs:
![image](https://user-images.githubusercontent.com/5324924/91083736-1192f200-e64b-11ea-8407-2757ef46538f.png)
Unfortunately it's not possible (yet) to access it from the GitHub API.

Of course I could [link an issue in the PR's description field](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) but that requires extra permissions.

Do you have any suggestions? What's your current workflow to do this?
