### ISSUE TITLE
Feature request: support for json settings

### ISSUE THREAD

**Issue by TGTGamer** [robvanderleek/create-issue-branch#220]
Title is fairly self-explanatory. Drop a line if you want a hand xD

(If I get time, I'll drop a PR)

**Comment by robvanderleek** [comment]
Hi @TGTGamer 

TBH I haven't seen any JSON-based Actions configurations so far, is this common in your experience?
You are the first to request support for this, so I give it a bit lower priority. Your PR for this is welcome of course! 😄

**Comment by TGTGamer** [comment]
Yeah JSON is becoming more popular slowly as we are moving away from bots and onto actions. 

A lot of actions I use now support the option to use JSON or yml, and I'm designing all of my actions to do the same. 

If I find time, I'll take a look at creating a pull request.
