### ISSUE TITLE
Suddently stopped working

### ISSUE THREAD

**Issue by jllodra** [robvanderleek/create-issue-branch#231]
Hello,

I have create-issue-branch installed as an app on all repositories, with a .github yml config.
Everything has been working for months, suddently today stopped working, I create Issues but no branch is created neither error message is given.

Do you have an idea of what could be happening?

Thanks in advance

**Comment by robvanderleek** [comment]
Hi @jllodra 

Thanks for the notification.

There seems to be a memory leak/consumption problem in the code that causes termination of the process by Heroku.
I've applied some bandaid (to get the App up again) but did not located the root problem yet.

TBC...

**Comment by robvanderleek** [comment]
Hi @jllodra 

I've upgraded the App to v10 of the Probot framework. According to the [release notes](https://github.com/probot/probot/releases/v10.0.0) v10 has a significant lower memory usage.
I'll keep an eye on the memory usage in production.

Thanks for your swift action to notify me about the downtime.
Rob

**Comment by jllodra** [comment]
Thank you, @robvanderleek
