### ISSUE TITLE
Slash CIB command stopped working

### ISSUE THREAD

**Issue by lexdewilligen** [robvanderleek/create-issue-branch#236]
The app has been working perfectly for a while. However, something must have changed, because if we use /cib, no branches are created anymore. The app does still auto close issue's after PR's are merged, so it's not completely broken. I've tried to reinstall the app, but the problem is still the same.

**Comment by robvanderleek** [comment]
Hi @lexdewilligen 

Sorry to hear you're having issues with the App.
There have been some [stability issues](https://github.com/robvanderleek/create-issue-branch/issues/231) the last couple of days but those have been resolved yesterday.

I've just tried the `/cib` command myself and that worked:
![image](https://user-images.githubusercontent.com/5324924/93801308-1646c800-fc42-11ea-8550-e71c3341d871.png)

Can you please give it another go?
Let me know if stuff is still broken for you of course.
Rob

**Comment by lexdewilligen** [comment]
We used the installed app version. That didn't work the couple of last weeks. However, we've now installed it as an action and that seems to work fine. Just one quick question, we also use the autoCloseIssue option, shouldn't the action then also run on: 
```
pull_request:
    types: [closed]
```
I can't seem to find this anywhere in the docs.

**Comment by robvanderleek** [comment]
Hi @lexdewilligen 

Thanks for the configuration feedback, I've updated the README.

If you can share details, I'm interested in the problems you experienced with the App. There were some memory issues but the total downtime lasted about a day.

Rob
