### ISSUE TITLE
Access to github actor?

### ISSUE THREAD

**Issue by robertp** [robvanderleek/create-issue-branch#238]
Thanks for your action, it rocks :) 

Question: Is there an easy way to access the event initiator/slash comment creator? I'd like to be able to optionally name the branch something like:
`'${github.actor}/${issue.number}.${issue.title,}'`

Thanks!

**Comment by robvanderleek** [comment]
Hi @robertp 

Thanks for the compliment 😄 

According to the [webhook event documentation](https://developer.github.com/webhooks/event-payloads/#issue_comment), the user that triggered the event should be available in the `sender` object.
This is an example of such an object:
```json
  "sender": {
    "login": "robvanderleek",
    "id": 5324924,
    "node_id": "MDQ6VXNlcjUzMjQ5MjQ=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/5324924?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/robvanderleek",
    "html_url": "https://github.com/robvanderleek",
    "followers_url": "https://api.github.com/users/robvanderleek/followers",
    "following_url": "https://api.github.com/users/robvanderleek/following{/other_user}",
    "gists_url": "https://api.github.com/users/robvanderleek/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/robvanderleek/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/robvanderleek/subscriptions",
    "organizations_url": "https://api.github.com/users/robvanderleek/orgs",
    "repos_url": "https://api.github.com/users/robvanderleek/repos",
    "events_url": "https://api.github.com/users/robvanderleek/events{/privacy}",
    "received_events_url": "https://api.github.com/users/robvanderleek/received_events",
    "type": "User",
    "site_admin": false
  }
```
Based on this `'${sender.login}/${issue.number}.${issue.title,}'` should work for event initiators/slash comment creators.

Can you try it out and let me know?

**Comment by robertp** [comment]
Hey @robvanderleek thank you! I'll try it and let you know.

**Comment by robertp** [comment]
@robvanderleek works great, thanks!
