### ISSUE TITLE
Feature request: custom comment message on branch created.

### ISSUE THREAD

**Issue by bubkoo** [robvanderleek/create-issue-branch#281]
Custom comment message to replace the default comment `"Branch xxx created!"`.

**Comment by robvanderleek** [comment]
Hi @bubkoo 

Can you tell a bit more about your use-case for this feature? Why do you want to replace the default comment? (or should there perhaps be a different default?)

KR, Rob

**Comment by bubkoo** [comment]
@robvanderleek such as adding _contributing guid_ in the comment.

**Comment by robvanderleek** [comment]
Do you expect to have access to the name of the branch in the comment message? Such as: 'Thank you for creating branch ${branchName}!'

Perhaps a better solution for your use-case: there's another App called Welcome that allows you to define messages for new users after opening an issue/PR: https://github.com/behaviorbot/welcome
The benefit of this ☝️ App is that the message is only displayed once for a user.

**Comment by bubkoo** [comment]
The [welcome](https://github.com/behaviorbot/welcome) App only welcome user for the first issue/PR. 

'Thank you for creating branch ${branchName}!' is awesome.

**Comment by robvanderleek** [comment]
Hi @bubkoo 

I've add a configuration option for a custom comment message, please see the [Readme](https://github.com/robvanderleek/create-issue-branch#change-message-in-issue-comments).

Thanks for your feedback
Let me know if your run into any issues 😄
