### ISSUE TITLE
Could not create branch (Reference update failed)

### ISSUE THREAD

**Issue by MichaelGatesDev** [robvanderleek/create-issue-branch#303]
I installed this app to my organization but I'm receiving this error upon assigning an issue to myself:

```
Could not create branch (Reference update failed)
```

![image](https://user-images.githubusercontent.com/10709067/103229528-2fc27480-4901-11eb-9a4e-9bae98916c9a.png)

**Comment by robvanderleek** [comment]
Hi @MichaelGatesDev 

Sorry to hear the app does not work for you. I checked the app logs, it's working fine for other users.

Maybe I can help, can you answer these questions:
Did you configure the app with a `.github/issue-branch.yml` file? If so, what are the contents of that file?
Do you use the app on github.com or a GitHub Enterprise server?

Kind regards, Rob

**Comment by MichaelGatesDev** [comment]
Hi @robvanderleek ,

I am using the app here on github.com and I did not create any configruation - I am using whatever's available out-of-the-box upon install.  It seems to work fine on my personal repos but not on the organization's repos which are private. Maybe they have to be public?

**Comment by robvanderleek** [comment]
The app works for public and private repos, both personal and organization repos. Or at least it should 😉 

Maybe it's a permission issue? You can check the App permission in the Organization Settings under: Installed GitHub App > Create Issue Branch Configure
It should look something like this:
![image](https://user-images.githubusercontent.com/5324924/103233009-45a15b00-493c-11eb-87a1-6ac342dbdffa.png)

It's weird that the App is able to comment on the issue but can't create a new branch.
What is the title of the issue that you are trying to create a branch for?

**Comment by MichaelGatesDev** [comment]
Yep i've given it access to all repos just like it shows there. The title is pretty insane, maybe that's why..

```
 "Error: Mysqli statement execute error : Cannot add or update a child row: a foreign key constraint fails (`omeka`.`omeka_super_eight_festivals_filmmaker_films`, CONSTRAINT `omeka_super_eight_festivals_filmmaker_films_ibfk_1` FOREIGN KEY (`filmmaker_id`) REFERENCES `omeka_super_eight_festivals_peop)" when adding filmmaker film #20 
```

I know it goes against some kind of standard to have a title this horrific.

**Comment by robvanderleek** [comment]
I ❤️  these corner-cases 😄 

I'll see if I can reproduce your issue. In principle the app should be able to handle valid GitHub issue titles (although Git & GitHub have their own restrictions for branch names of course).

**Comment by robvanderleek** [comment]
Hi @MichaelGatesDev

The app now limits branch names to 250 bytes (because that appears to be the limit:  https://stackoverflow.com/questions/60045157/what-is-the-maximum-length-of-a-github-branch-name)

Let me know if you keep having problems with the app, closing this issue for now.
Thanks for reporting!
