### ISSUE TITLE
Branch creation only for certain labels

### ISSUE THREAD

**Issue by mklilley** [robvanderleek/create-issue-branch#335]
I love the idea behind your Action. I see that you can [skip-branch-creation-based-on-issue-label](https://github.com/marketplace/actions/create-issue-branch#skip-branch-creation-based-on-issue-label) which is great but I'm wondering what about the case where you only want to create a branch for a specific label? In other words, if one doesn't always want to create issue branches by default?

Sorry if this is obvious and I missed it.

Thanks for your help.

Matt

**Comment by robvanderleek** [comment]
Hi @mklilley 

Not obvious at all! Had to fiddle a bit with the configuration myself.

A way to achieve this is with the branch configuration fall-through behaviour:

```yaml
branches:
  - label: bug
    skip: false
  - label: '*'
    skip: true
```

The configuration above only creates branches for issues with the label `bug`.
I've updated the [documentation](https://github.com/robvanderleek/create-issue-branch#matching-labels-with-wildcards).
Let me know if this works for your use-case.

KR, Rob

**Comment by mklilley** [comment]
Thanks @robvanderleek - I'll give that a go. I really appreciate you getting back to me so quickly. Have a good weekend.
