### ISSUE TITLE
Add signature support

### ISSUE THREAD

**Issue by sirwolfgang** [robvanderleek/create-issue-branch#338]
Right now the commits are unsigned, which blocks merge on repos that require signatures.

**Comment by robvanderleek** [comment]
Hi @sirwolfgang 

Are you referring to the empty commit created in a (draft) pull request? (such as the commit "Create draft PR" [here](https://github.com/robvanderleek/robvanderleek.github.io/pull/100))

**Comment by sirwolfgang** [comment]
@robvanderleek Yeah, I tried to look through it; It looks like the lib supports setting the signature but not familiar enough with the project to make the change.
