### ISSUE TITLE
Can the issue title be cleaned before branch creation?

### ISSUE THREAD

**Issue by brandondurham** [robvanderleek/create-issue-branch#350]
I occasionally use _issue titles with/forward/slashes/in/them_. Doing this creates a branch called `them` in `issue-titles-with/forward/slashes/in/`. Is it possible to strip or replace specific characters in an issue title?

**Comment by robvanderleek** [comment]
Hi @brandondurham 

Currently it's not possible to strip/replace specific characters in branch names.
There's the option to [not include the issue title in the branch name](https://github.com/robvanderleek/create-issue-branch#branch-names), would that work for your use-case?

[Some characters are replaced](https://github.com/robvanderleek/create-issue-branch/blob/0e8335fb7568a600c6ddaf21bdd606be27235d97/tests/utils.test.js#L52) to make branch names "git safe" but slash is allowed as you mention.

I'm a bit hesitant to add options for replacing/stripping characters in branch names but open for suggestions 😄
