### ISSUE TITLE
Link the PR generated to the issue in 'Linked pull requests'

### ISSUE THREAD

**Issue by pablo-de-andres** [robvanderleek/create-issue-branch#363]
Issues on GitHub have a 'Linked pull requests' section:
![image](https://user-images.githubusercontent.com/9430234/113106121-ad4c9800-9202-11eb-8a8d-c532a7ef9d61.png)
Similarly, PR have a 'Linked issues sections' (they are symmetric, setting one will update the other):
![image](https://user-images.githubusercontent.com/9430234/113106252-d79e5580-9202-11eb-9a6c-1ba1571f2ec6.png)
I think it would be a nice feature if the bot could also set the connection there when creating the branch and the PR.

**Comment by robvanderleek** [comment]
Hi @pablo-de-andres 😄 

This would be a nice feature indeed but I've looked before and can't find any endpoints to do this from the GitHub API (not in [pulls](https://docs.github.com/en/rest/reference/pulls) and not in [issues](https://docs.github.com/en/rest/reference/issues)).

Currently when the App opens a new (draft) PR, it links the PR to the issue using a comment:
![image](https://user-images.githubusercontent.com/5324924/113162184-5add9c80-923f-11eb-8906-775e4efc1673.png)

Do let me know if you can find a way to link issues and PRs using the API.

Kind regards,
Rob

**Comment by maxsoe** [comment]
@robvanderleek 

I noticed that in the API, there is a "pull_request" key in the GET response.

<img width="1532" alt="Screen Shot 2021-08-22 at 14 19 54" src="https://user-images.githubusercontent.com/3930197/130351721-fe41a5db-9a30-4ff7-a83b-07f15c34f4cb.png">

Does that help?

This might also help - https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types

Github states that pull requests are a subset/subclass of issues.

Gonna see what else I can dig up, but this could be a starting point for everyone else who's interested in this topic.

**Comment by maxsoe** [comment]
@robvanderleek 

Also came across this https://docs.github.com/en/enterprise-server@3.0/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

I'm too much of a novice to make heads or tails of it.

**Comment by robvanderleek** [comment]
Hi @maxsoe 

Thanks for digging into this 😄 

The last link you posted shows how to link Issues and PRs via comments/descriptions, and manually via the Web UI. It does not offer a way to link Issues and PRs via the API (please correct me if I'm wrong).

The App can automatically [create a (draft) PR from an Issue](https://github.com/robvanderleek/create-issue-branch#automatically-open-a-pull-request). When that happens the Issue and PR are linked via the first (empty) commit in the new PR branch.

However, when a user creates a PR for an Issue created by the App and merges that PR, there's no way to link the two together via the API. Before closing the Issue I could first add a comment in the Issue that links the Issue to the merged PR, but I find that workflow very awkward.

Let me know your thoughts on this. We can also setup a branch that implements the behaviour described above so you can try it out.

**Comment by robvanderleek** [comment]
Hi @bilcus 

I noticed that GitHub now links issues and PRs based on auto-linking keywords in commit messages. For example, see [this issue](https://github.com/facio-ergo-sum/test-repo-create-issue-branch-prod-app/issues/11) that was linked bi-directionally to the PR.

Can you also confirm this behaviour? Then this issue can finally be closed 😄
