### ISSUE TITLE
Submitting a new issue is not triggering the create a new branch event

### ISSUE THREAD

**Issue by alperendurmus** [robvanderleek/create-issue-branch#367]
I submitted a new issue but the workflow has failed.

![image](https://user-images.githubusercontent.com/44159011/113862861-a1884500-97b1-11eb-8120-a3081a11a3aa.png)

**Comment by alperendurmus** [comment]
This is probably about the paid plan. I am using a company account.
https://github.com/robvanderleek/create-issue-branch/pull/366/

**Comment by robvanderleek** [comment]
Hi @alperendurmus 

Oops, I think I know what's going on.
I pushed a fixed to not check the Marketplace plans in case CIB is running as a GH action.

Is it working again?

**Comment by alperendurmus** [comment]
Umm. Looks like it is working now. I will update you if somehow it stops again.
