### ISSUE TITLE
About using app in our student non-profit organisation

### ISSUE THREAD

**Issue by xHeler** [robvanderleek/create-issue-branch#371]
We are using your helpfull bot in our organisation named: Pwr In Space. We are group of students whose develop, codding, discovery new features. You can find more information about organisation at: http://pwrinspace.pwr.edu.pl/. Thanks a lot.

**Comment by robvanderleek** [comment]
Hi @xHeler 

Sounds interesting, I'll add your organisation to the list of free Pro subscriptions 😄  What is the GitHub name of your org? I could not find it by searching for "Pwr In Space"

Rob

**Comment by xHeler** [comment]
Sorry, little mistake. Organisation name: PwrInSpace. https://github.com/PWrInSpace/. Thanks a lot Rob.
