### ISSUE TITLE
Request a free plan for a non-profit institution

### ISSUE THREAD

**Issue by RCout1nho** [robvanderleek/create-issue-branch#376]
I would like to apply for a free plan for nonprofits. I am part of the organization [Codemeistre](https://github.com/codemeistre), we are an organization of students and professors at the Federal University of Amazonas (UFAM), Brazil.

We developed an online judge system for computer courses called [Codebench](http://codebench.icomp.ufam.edu.br), used at our university. We are currently developing a new version for this system built with React and NestJS.

Create-issue-branch is helping us a lot in the process of organizing branchs to resolve issues, I ask that if possible analyze our request with care.

Att. Codemeistre.

**Comment by robvanderleek** [comment]
Hi @RCout1nho 

Thanks for the clear background info! 😄 

I've upgraded [Codemeistre](https://github.com/codemeistre) to a free Pro plan, good luck!

Best regards, Rob

**Comment by RCout1nho** [comment]
Thank you very much Rob
