### ISSUE TITLE
Request free plan for RaspberryPiFoundation / astro-pi

### ISSUE THREAD

**Issue by patch0** [robvanderleek/create-issue-branch#378]
HI there

I was hoping to be able to secure a free plan for the [RaspberryPiFoundation](https://github.com/RaspberryPiFoundation/) and [astro-pi](https://github.com/astro-pi/) organizations.  The Raspberry Pi Foundation is a UK-based charity focussing on computing and digital making around the world. Our Astro Pi project is just one part of that, allowing children to run their computer programs on the international space station.

We've found this action to be super useful, helping to streamline workflows.

Thanks!

**Comment by robvanderleek** [comment]
Hi @patch0 

I'm honoured to be able to support these projects a bit 😄 

Kind regards,
Rob

**Comment by patch0** [comment]
Thank you 😊
