### ISSUE TITLE
Usage of this github action in the context of a DevOps university course

### ISSUE THREAD

**Issue by duchainer** [robvanderleek/create-issue-branch#395]
Hi, I'm student from École de Technologie Supérieure in Montréal. 
I have seen the create-issue-branch bot message about possible non-profit organisation and just wanted to know if it included students in a same team.

Your github action would make our experience closer to the current Gitlab workflow and more in the spirit of DevOps.

We are 3 students in our team and the course will end at the end of august. We would use it in 2 repos, one for 4 weeks which is https://github.com/LOG680-01-Equipe-09/LOG680-lab1 ,and the other for the rest of the session of class (not created yet).

Don't hesitate if you need more informations. Here is the course description, unfortunately only in french : https://www.etsmtl.ca/etudes/cours/LOG680

Have a great day.

**Comment by robvanderleek** [comment]
Hi @duchainer 

I've added the organization [LOG680-01-Equipe-09](https://github.com/LOG680-01-Equipe-09) to the list of free Pro plans.

My French is not that great but from what Google translate shows it looks like a pretty interesting course 😄 Good luck!

Best regards,
Rob
