### ISSUE TITLE
Paid subscription....

### ISSUE THREAD

**Issue by bennelmes** [robvanderleek/create-issue-branch#405]
Hi there,

We've been receiving this message, and are a not-for-profit. As instructed, I'm contacting you. Any way we could talk about plans?

![image](https://user-images.githubusercontent.com/69809507/118961576-5e96c100-b95c-11eb-8a42-120fea43543a.png)

Best,
Ben

**Comment by robvanderleek** [comment]
Hi Ben,

Sure! Tell me a bit about your organization (just what you are building/using GitHub for) and also include the GitHub handle. For inspiration you can look at the previous requests: https://github.com/robvanderleek/create-issue-branch/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Request+for+free+Pro+plan%22

Kind regards, Rob

**Comment by bennelmes** [comment]
Hi Rob,

We're a non-profit organisation researching the transition to electric vehicles in the UK. We're building some tools to open up vehicle data in the UK. You can view some of these at www.newautomotive.org/ecc, for example (draft next version at newautomotive.org/ecc-v2). We're grant funded, and legally structured as a Community Interest Company, so we don't / can't make a profit.

Our handle is: https://github.com/orgs/New-AutoMotive

Best,
Ben

**Comment by robvanderleek** [comment]
Happy (and honoured) to support that work Ben! I've added your org to the list of free Pro plan users.
KR, Rob
