### ISSUE TITLE
Changing the default branch

### ISSUE THREAD

**Issue by cedsmit** [robvanderleek/create-issue-branch#409]
currently i'm having the issue that once i create a  issue and assign it to someone the app always takes my default branch (main)
even if there are no labels applied to the issues.

wouldnt it be cool to have a argument in the configuration to just set the default branch that you would like.

something like : defaultbranch: dev

**Comment by pablo-de-andres** [comment]
You can do that if you use a wildcard for the labels ([here](https://github.com/robvanderleek/create-issue-branch#matching-labels-with-wildcards)):
```yml
branches:
  - label: '*'
    name: dev
```

**Comment by robvanderleek** [comment]
Hi @cedsmit 

Apologies for the late reply (was on a short break). Thanks for your feedback.
What do you think of the configuration solution offered by @pablo-de-andres ?

KR, Rob

**Comment by cedsmit** [comment]
hey @robvanderleek 

dont worry i was gone for a few days also :)

And the offered solution would help me but i'm wondering what if i wanted too use that wildcard for something else. can i use 2? or am i limited too one. cause that solution looks more like a bandaid fix too me

**Comment by robvanderleek** [comment]
Hi @cedsmit 

I've added the [configuration option you suggested](https://github.com/robvanderleek/create-issue-branch#default-source-branch), that's indeed much nicer than the label-hack.

Let me know if you run into any issues with this.
