### ISSUE TITLE
Can't uninstall create-issue-branch

### ISSUE THREAD

**Issue by baptistedec** [robvanderleek/create-issue-branch#415]
Hi!
I'm currently in a student project in the Epitech Organization (a French school of computing).
I tried to install your bot to simplify the issues management of our project.
I realised that you were blocking the bot for repos in organisations. So I tried to delete the bot by deleting the yml file.
Apparently, it didn't work and I still get the bot's emails and comments for every event on an issue.

I already tried to delete the bot from my repo, my settings:
![image](https://user-images.githubusercontent.com/57908760/120803508-e88d7f00-c543-11eb-8e1f-4643b7128522.png)

**Comment by robvanderleek** [comment]
Hi @baptistedec 

Sorry to hear your issues with the bot, perhaps I should add a section to the README how to uninstall the app (🤔 ).

Can you try if this link: https://github.com/settings/installations/7740930 takes you to the app configuration page?
At the bottom of that page there's a button to uninstall the Create Issue Branch app.
Another way to get to the page is `Settings > Applications > Installed GitHub Apps > Create Issue Branch > Configure`

Before you hit delete, are you aware of the free Pro plan option for non-profit usage? This app indeed requires a paid plan for private org repositories but if you're using it for a school project I would be more than happy to add that organization to the allow list. If you want this let me know the org name 😄 

Kind regards, Rob

**Comment by baptistedec** [comment]
Hi @robvanderleek

Thank you and sorry for the delay !

I tried to go to your link, but i haven't the Create Issue Branch app in the list.  Same for the App in my project and in my organization.

Although at first I would have liked to delete the application. I wasn't aware of the free Pro plan option but it could be very useful for us. 
Indeed, it's a school project for [Epitech](https://www.epitech.eu). The organization name is [EpitechMscPro2020](https://github.com/EpitechMscPro2020) ! 😄

Regards, Baptiste

**Comment by robvanderleek** [comment]
Hi @baptistedec 

I've added your org to the free Pro plan, happy coding! 😄
