### ISSUE TITLE
issue labels are not transfered to PR

### ISSUE THREAD

**Issue by jezscha** [robvanderleek/create-issue-branch#422]
Hey this workflow is really awesome! I haven't found the way to automatically transfer labels and assigned user to PR from source issue. Is there some way to do it? 

Thank you for an advice ;)

**Comment by robvanderleek** [comment]
Hi @jezscha 😄 

Happy to hear you like the app.

Can you tell me a bit more about your workflow? Do you have Create Issue Branch configured to automatically open a (draft) PR? Currently I do not copy the labels from the issue to the PR (not sure if that is a common practice) but it sounds like it would make sense and not that hard to implement.

Kind regards. Rob

**Comment by jezscha** [comment]
Hey @robvanderleek thanks for quick reply. In the workflow the `draftPR` is on. From what I see this would be great optional argument for copying labels issue to PR or move assigned person from issue to PR. But I don't deny it might not be a standard workflow, but for me it is.

Thank you Jakub

**Comment by robvanderleek** [comment]
Hi @jezscha 

For now I've added two configuration options that can be used to copy over labels and assignee from the issue to the PR. Please also see the [README](https://github.com/robvanderleek/create-issue-branch#copy-labels-and-assignee-from-issue).

Thanks for your feedback! Perhaps this behaviour can be the default some day (TBH I don't understand why issues and PRs do not share these fields already in GitHub when the issue and the PR are linked).

Let me know of course when you experience any problems with the new configuration options.

**Comment by jezscha** [comment]
This looks great, thanks a lot @robvanderleek! Yeah, I agree that this should be Github's feature.
