### ISSUE TITLE
Rename app

### ISSUE THREAD

**Issue by paced** [robvanderleek/create-issue-branch#44]
Okay, this is going to sound like a _major_ trivial thing. But all of my current GitHub Apps use an Uppercase Format type of app name while this one is called "create-issue-branch".

Could it be called "Create Issue Branch" instead? Or something like "Autobranch"?

**Comment by robvanderleek** [comment]
Hi @paced 
Sometimes the little things are important 😄 
I think I can rename the app to "Create Issue Branch" but need to check the impact. "Auto Branch" is already taken by a different app (https://github.com/marketplace/auto-branch).

Can you show/tell me on what view you are looking at that shows the inconsistency in naming?

**Comment by paced** [comment]
I've actually used Autobranch, this is better since it allows customisation :).

I see it when looking in my organisation's settings as "Installed GitHub Apps":

![image](https://user-images.githubusercontent.com/15013453/68757638-5e7b7e00-0660-11ea-983c-e38ac3a8304d.png)

Thanks!

**Comment by robvanderleek** [comment]
I've renamed the app, looks consistent with other apps now:
![image](https://user-images.githubusercontent.com/5324924/68897307-8ab10080-072d-11ea-9fa1-28d02cfe1f5e.png)

Thanks for reporting this!

**Comment by paced** [comment]
Thank you for fixing this and for making GitHub more usable through your app!
