### ISSUE TITLE
Copy an Issue's Description in Its PR in a Comment

### ISSUE THREAD

**Issue by benoit-dubreuil** [robvanderleek/create-issue-branch#466]
## Use case
I use specific keywords, such as `Depends on #my-issue-number`, in issues to indicate that they depend on other issues and pull requests. Those keywords can be used multiple times to indicate many dependent issues and pull requests. Then, a GitHub Action named [Dependent Issues](https://github.com/marketplace/actions/dependent-issues) find those keywords and act upon them. For example, a pull request cannot be merged if its dependent issues and pull requests aren't closed / merged.

## Problem
I can't find an easy way to share an issue's dependencies with its pull requests.

## Propositions
1. [Simple] Copy an issue's description into its pull requests' descriptions when they are created.
2. [Complex] When creating a pull request for an issue, search through that issue's description the specific keywords and copy those keywords into the pull request's description.

## Questions
- ~~Could it be possible to only use issue numbers as dependencies for issues and pull requests numbers as dependencies for pull requests? That would require a one to many mapping from issue numbers to pull request numbers.~~

**Comment by robvanderleek** [comment]
Hi @benoit-dubreuil 😄 

Thanks for your feedback! (maybe I should include a template for Issues in the repo 🤔 )

Solution 1 is not hard to implement, perhaps something this App could even have as a default.
Unfortunately I don't fully understand your question at the end.

I can implement the proposed simple solution in a branch and give you access, then we can test the workflow for real. Would that be OK?

Kind regards,
Rob

**Comment by benoit-dubreuil** [comment]
Hello @robvanderleek,

> Solution 1 is not hard to implement, perhaps something this App could even have as a default.
That's great 🚀

> Unfortunately I don't fully understand your question at the end.
Maybe real test cases will explain my thoughts better. Please, look at the following issue and its pull request:
- https://github.com/ChevryGames/cg-math/issues/39
- https://github.com/ChevryGames/cg-math/pull/40

> I can implement the proposed simple solution in a branch and give you access, then we can test the workflow for real. Would that be OK?
That would be OK. Thank you for your time and work.

Regards,
Benoît Dubreuil

**Comment by benoit-dubreuil** [comment]
https://github.com/ChevryGames/cg-math/issues/48
 
Treat this comment as if it was some sort of  "!Remind me".

**Comment by benoit-dubreuil** [comment]
> Are you using the App or the Action?
I am using the App.

I now begin the tests for the feature.

**Comment by benoit-dubreuil** [comment]
Hi @robvanderleek

It works 👍

### Test case
Issue: https://github.com/ChevryGames/cg-math/issues/51
PR: https://github.com/ChevryGames/cg-math/pull/52

**Comment by benoit-dubreuil** [comment]
> I would like to keep this functionality under a feature flag (just like copying over labels and assignees from the Issue, as discussed in the [README](https://github.com/robvanderleek/create-issue-branch/tree/0e95201b9a528c6a3d7f3f3bdddf4da5679ede1f#copy-description-labels-and-assignee-from-issue)), do you agree?

Of course, no problem. It makes the most sense with your conventions in place.

Thanks again

**Comment by robvanderleek** [comment]
I've merged the branch to main, let me know if you spot any issues.

Best, Rob
