### ISSUE TITLE
My issue number increases 2 not 1 :( 

### ISSUE THREAD

**Issue by earth-h** [robvanderleek/create-issue-branch#484]
Hello, I have a question when using Create-issue-branch github action.
I just newbie for github action. 

My repo name: earth-TIL-algorithm 

I just make .github/issue-branch.yml and .github/workflow/issue-branch.yml.

When I make an issue and PR to merge the automate branch(feature/#issue.num), issue close.  (That was fine)

But when I make an issue again, issue number increase 2… 
(ex. First issue number 4 and next issue number 6)

I don’t know why this happend. Please let me know how to fix it. 

Thank you.

**Comment by earth-h** [comment]
PR make my issue num + 2.. 
Thank you for making good action !

**Comment by robvanderleek** [comment]
Hi @earth-h 

You already figured it out 😄 At Github [every pull request is an issue](https://docs.github.com/en/rest/reference/pulls) indeed so they share issue numbers.

Thanks for the compliment,
KR, Rob
