### ISSUE TITLE
How to customize branch names?

### ISSUE THREAD

**Issue by notevery** [robvanderleek/create-issue-branch#490]
![image](https://user-images.githubusercontent.com/12843847/135474250-428792bf-e107-479f-824f-835b855c7dd1.png)

Where to put this code?

**Comment by robvanderleek** [comment]
Hi @notevery 

Configuration for the Action needs to be placed in a YAML file: `.github/issue-branch.yml`
You can put that file either in the repo or in a special repository called `.github`
Please look in the documentation: https://github.com/robvanderleek/create-issue-branch/#configuration

Hope this answers your question.
KR, Rob

**Comment by notevery** [comment]
Very grateful for your help！！！
As you can see, my English level is relatively poor, do you have any plans to support Chinese issue name?

**Comment by robvanderleek** [comment]
Happy to help 😄 

In theory `create-issue-branch` should support Chinese issue names but I've never tried it or see anyone do that.

It would be great if you tried using it with Chinese issue names and let me know if it works or crashes 😄 

Kind regards, Rob

**Comment by notevery** [comment]
@robvanderleek
There are two situations, one is all Chinese, and the other is half Chinese and half English. Chinese was eaten ！！！ 

<imgwidth="563" alt="WechatIMG337" src="https://user-images.githubusercontent.com/12843847/135700873-fd220312-cc92-48b8-a647-7ad01b7e366f.png">

 
<img width="543" alt="WechatIMG338" src="https://user-images.githubusercontent.com/12843847/135700965-a641ff3e-e4b0-4baf-a779-0b3e84a082e9.png">

**Comment by robvanderleek** [comment]
Hi @notevery 👋 

I hope to have fixed your issue in the current deployment.
Chinese characters are no longer eaten by the regular expressions in the code.

Would be great if you could test it out and let me know if it works for you.

Thanks a lot for you feedback!
Best regards,
Rob
