### ISSUE TITLE
Feature request: Choose target branch

### ISSUE THREAD

**Issue by skazazes-work** [robvanderleek/create-issue-branch#511]
Hello, I have a feature request I would like to discuss.

My repository is currently organized as follows. There is a main and development branch, with features and bugfixes set to branch from develop, and hotfixes from main. 

I would also like to add support to the repo for creating automated releases. I want to create an issue with a label release/<major|minor|patch> and have a relevant branch created off develop. This branch is then used for any last minute organizational changes and additions needed for the release, with notes and other conversation happening in the PR. Upon closing this PR , I would like the code to be merged into the main branch.

My current solution is to create the release branches off of the main branch, manually merge develop into this release branch and finally close the PR. This does allow the triggering of my release workflows, but ultimately I want to be able to create the issues, make the few changes required and close the PR without manually merging develop. 

This should enable branching from main and triggering release workflows without the need to manually merge in the develop branch.

**Comment by robvanderleek** [comment]
Hi @skazazes-work 

Thanks for describing your workflow in detail 🙂 

Currently CIB can do 2 of the things you describe:
1. [Select a source branch based on an issue label](https://github.com/robvanderleek/create-issue-branch#source-branch-based-on-issue-label), so for all `release/*` labels you could set the source branch to `develop`
2. Enable the automatic [creation of a (draft) PR](https://github.com/robvanderleek/create-issue-branch#source-branch-based-on-issue-label), note that this is a global flag

It's not yet possible to configure the target branch for the PR created in step 2, this could be added as an optional `prTarget` field in the branch configuration.

What do you think?

**Comment by pietrovismara** [comment]
Sorry for the necro but I like the idea of an optional `prTarget` and I would use it in my workflow

**Comment by robvanderleek** [comment]
Hi @pietrovismara 

The `prTarget` is now a configuration option, please the the README: https://github.com/robvanderleek/create-issue-branch#pull-request-target-branch-based-on-issue-label

Let me know if you bump into any issues.

KR, Rob
