### ISSUE TITLE
Could not create branch `branch` due to: Invalid request.  "sha" wasn't supplied

### ISSUE THREAD

**Issue by 949mac** [robvanderleek/create-issue-branch#518]
Any ideas here:

![image](https://user-images.githubusercontent.com/23151962/140799903-26a473ce-1fb2-4e41-ab31-0f0a01ddaa00.png)

Thanks!

**Comment by 949mac** [comment]
Whoops! My ooooooold test repo used a branch name of `master` rather than `main`

```
mode: chatops
defaultBranch: main
branchName: '${issue.number}-${issue.title}'
silent: false
autoCloseIssue: true
gitSafeReplacementChar: '-'
```

**Comment by robvanderleek** [comment]
I'll have a look if I can improve the error message 😉 

KR, Rob
