### ISSUE TITLE
Non-profit organization: University of Illinois at Urbana Champaign

### ISSUE THREAD

**Issue by robertslater1976** [robvanderleek/create-issue-branch#524]
Hi!

I work for the University of Illinois at Urbana Champaign. We're a not for profit, and we've been using your excellent tool for while now. Would you be willing to (re-)authorize it for use in our private repo?

**Comment by robvanderleek** [comment]
Hi @robertslater1976 

My honour to support your department's work, what is the GitHub organization name that I can add to the Free pro plan list?

**Comment by robertslater1976** [comment]
Awesome! You rock!

https://github.com/web-illinois

**Comment by robvanderleek** [comment]
Should work now 👍

**Comment by robertslater1976** [comment]
It does, perfectly! Thank you so much. :)
