### ISSUE TITLE
University lab org

### ISSUE THREAD

**Issue by cooperlab** [robvanderleek/create-issue-branch#528]
Hello @robvanderleek,

Thank you for making such a valuable tool.

We are a research lab at Northwestern University working with students to develop software tools - https://github.com/PathologyDataScience. I would like to use create-issue-branch in our repositories.

**Comment by robvanderleek** [comment]
Hi @cooperlab 👋 

I've added your GitHub org to the list of free Pro plans 😄 

Happy and honoured to be able to support your research group this way.

Kind regards,
Rob
