### ISSUE TITLE
Set branch name including the date

### ISSUE THREAD

**Issue by eProw** [robvanderleek/create-issue-branch#530]
Hello everyone!

My question was about setting a branch name with an specific date, or the current one (in a format similar to ddmmYYYY for example, excluding time of day), so it can be used to track branches for a specific sprint through development.
The way it could work would be like:

branchName: 'S-${ date }-${ issue.number }-${ issue.title }'

Although I am still not very familiarized with Github Actions, maybe there is a direct way of doing this.
Do you know if this is supported?

**Comment by robvanderleek** [comment]
Hi @eProw 😄 

Currently only placeholders from the [issue payload](https://github.com/robvanderleek/create-issue-branch/blob/main/tests/test-fixtures/issues.assigned.json) are supported.
For example, you can prefix the branch name with the full issue creation timestamp like this in your configuration YAML:

```yaml
branchName: '${issue.created_at}-${issue.number}-${issue.title}'
```

The configuration above creates branch names like: `2021-09-13T05_49_05Z-123-This_is_a_bug`

Unfortunately other placeholders are not available, let me know if you would like this feature (and how you would expect it to work).

KR, Rob

**Comment by eProw** [comment]
Hello! Thank you so much for your answer! 

That is a feature I was looking for, I think it is useful because thanks to that, I could for example automate the process of creating some branches to set up a sprint for my project in a specific day.

In my case, I have a Trello board that is synchronized with my github project through Zapier, so every time I move a card into the 'DOING' column, a new issue is created and thanks to this application a new branch is created too.

What I want to achieve is, for example, a configuration in the app that only do 2 tasks: 

- A request to create a branch for the current day (e.g. Sprint25-11-2021) every time an issue is created (because of this branch would be already created with the first request, the rest of the issues would only do the second task)

- A request to create a branch for a specific issue (e.g. Sprint25-11-2021/issue-5-unit-testing) taking the specific branch of that day as the default branch, so a branch system is created for the sprint planned in that day.

In the end, it would look similar to this, but with dates instead of numbers:

![scrum-branching-strategy-1.jpg](https://user-images.githubusercontent.com/17097203/143519225-8038612e-29bd-4e6c-9071-cbb911d10039.jpg)

It takes advantage of assigning tasks on a specific day, so there is an unique branch that can gather all the tasks taken on a planned starting sprint day, making things easier for projects that make use of scrum or kanban development methodologies.

The only new parameter used in here is the date, which could be a substring of the issue.created_at placeholder.

Do you think this feature could be useful?

**Comment by robvanderleek** [comment]
Thanks for the detailed explanation of your workflow 👍 

A possible way forward to support this is to allow arbitrary environment variables as placeholder values.
This would only work if you run Create Issue Branch as a GitHub Action.

How that would look in your Actions workflow file (haven't tested this):

```yaml
steps:
      - name: Set Sprint date value
        run: |
          today=$(date +'%d-%m-%Y')
          echo "SPRINT_DATE=$today" >> $GITHUB_ENV
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Your configuration YAML could then refer to this environment variable:

```YAML
branchName: '${%SPRINT_DATE}-${issue.number}-${issue.title}'
```

What do you think about this?

**Comment by eProw** [comment]
This approach solves completely my problem!
The way that this could be adapted so each branch can come from the sprint branch of that day is by creating two Github Actions, one of them creates for example the S26-11-2021 branch, and the other one creates the branch for a specific issue.

**Comment by robvanderleek** [comment]
Hi @eProw 

To be clear, the example I gave above does not work yet.
Currently CIB does not support placeholders from environment variables.
I will start working on this though, should not be that difficult.

KR, Rob

**Comment by eProw** [comment]
Mea culpa, I was so convinced that it could work with no problems at all :sweat_smile:

**Comment by robvanderleek** [comment]
Hey @eProw 👋 

I've implemented [the functionality](https://github.com/robvanderleek/create-issue-branch#substitution-placeholders).

Could you give it a go and let me know if this works for your use-case?

**Comment by eProw** [comment]
Really works as expected, in the case of today, it tries to create a branch called S29112021 every time a new issue is found, and that was essentially what I needed.
Thank you so much @robvanderleek !!
