### ISSUE TITLE
Limit for branch name

### ISSUE THREAD

**Issue by flamisz** [robvanderleek/create-issue-branch#534]
Hi @robvanderleek,

it's me again.

I know there are some options customizing the branch names, but I'd like to have one more 😄 

Our issue titles are too long, so would be great if I could limit the branch name for words or characters. The best option would be if I could limit the words from the `issue.title` itself.

Maybe an extra operator (like the lowercase one, so the `interpolate` could limit that part. Or just a simple char limit that can overwrite the `MAX_BYTES_GITHUB_BRANCH_NAME`?

What are your thoughts on this?

🙇‍♂️

**Comment by robvanderleek** [comment]
Hi @flamisz 😄 

The confusing thing about the `MAX_BYTES_GITHUB_BRANCH_NAME` limit is that it [limits bytes](https://stackoverflow.com/questions/60045157/what-is-the-maximum-length-of-a-github-branch-name), not characters (some characters take up > 1 byte).

We could introduce another substitution operator, perhaps the string slicing notation that Python has (e.g.: `'hello'[1:3] == 'el'`) would be a fit.

What do you think?

Rob

**Comment by flamisz** [comment]
Sounds good to me, thanks. 👍

**Comment by robvanderleek** [comment]
Hi @flamisz 

I've implemented a string slicing operator, please [see the README](https://github.com/robvanderleek/create-issue-branch#substitution-value-slicing).

Let me know if this works for your use-case 🙂 

Rob

**Comment by flamisz** [comment]
Thanks, it's very useful :)
