### ISSUE TITLE
Filtering Bad Chars

### ISSUE THREAD

**Issue by sirwolfgang** [robvanderleek/create-issue-branch#550]
Is there a way we can filter additional non-git limited characters? Like ones that break bash/zsh?

Having to through `"` around a branch on checkout is a PTA, compared to just filtering out `&`, etc...

**Comment by robvanderleek** [comment]
This should be possible with the configuration option `gitReplaceChars`. Any characters you define there will be replaced in the branch name by the replacement character. Read more about this option in in the [Readme](https://github.com/robvanderleek/create-issue-branch#configure-replacement-character-and-replace-arbitrary-characters).

Can you give it a try and let me know?

**Comment by sirwolfgang** [comment]
Thanks, yeah this seems to be working. It might be worth extending the built-in list to include `&` and `>`. I am finding these imported via automatic bug tickets.
