### ISSUE TITLE
Specifying Pull Request Template

### ISSUE THREAD

**Issue by rubendinho** [robvanderleek/create-issue-branch#571]
Hi - is it possible to have the created PR use a Pull Request template?

**Comment by robvanderleek** [comment]
Hi @rubendinho 

Interesting question.
GitHub [supports PR templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) for PRs that are created interactively.
Of course this App creates PRs automatically, so there's no opportunity for the developer to fill in parts of the template.
API support for templates [seem to be lacking](https://github.community/t/rest-api-for-issues-and-pull-request-templates/14535) but arbitrary text can be added to the PR description through the API.

Can you perhaps explain your development workflow and the use-case for this?

Kind regards,
Rob
