### ISSUE TITLE
Don't create invalid file paths for Windows

### ISSUE THREAD

**Issue by danhallin** [robvanderleek/create-issue-branch#572]
It seems the default replaceChars allow branches to be created that cannot be fetched on Windows.

For example '>' was allowed which gives an invalid path on Windows.

Should replace at least <>:|?* by default or document that it should be done when used on Windows systems.

https://stackoverflow.com/a/31976060/1466346

**Comment by danhallin** [comment]
I solved the problem by overriding the setting. Including <, > and | should help future users not accidentally creating unfetchable branches.

**Comment by robvanderleek** [comment]
Hi @danhallin 

The default list now includes  `<`, `>` and `|`.

Thanks for the suggestion.
