### ISSUE TITLE
Running this action on a self-hosted running behind a proxy

### ISSUE THREAD

**Issue by cignatow** [robvanderleek/create-issue-branch#591]
I am trying to get this action to run on a self-hosted runner that is behind a company proxy and I think it's causing issues. When the action gets to the `Create Issue Branch` step, it hangs for a while and then I eventually get an error that looks like this:

`Error in app configuration: Exception while parsing configuration YAML: request to https://api.github.com/repos/cignatow/my-private-repo/contents/.github%2Fissue-branch.yml failed, reason: connect ETIMEDOUT 140.82.113.6:443`

I have looked around online and it seems that this `ETIMEDOUT` error is common for machines behind a proxy and I can't seem to figure out how to get it to run. Is there any way to pass `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables into the docker image that gets built? Or what issue could be causing this error if it's not a proxy issue?

I would really love to use this action for its automatic Pull Request creation feature.

**Comment by robvanderleek** [comment]
Hi @cignatow 

Interesting use-case 🙂 

I have no experience with this type of deployment but found some documentation how to setup [a proxy server with self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/using-a-proxy-server-with-self-hosted-runners). Since this action is packaged as a Docker container I guess also the last part on that page is relevant.

The error message you included is one of the first calls (probably the first) the action does to the GitHub API (it looks for the existence of a `issue-branch.yml` configuration file.

Hope this helps,
KR, Rob

**Comment by cignatow** [comment]
Thank you for the quick reply! I will check out the link you gave. I assume that if the `issue-branch.yml` file does not exist, then it will continue on anyway?

**Comment by robvanderleek** [comment]
Short follow-up: the reason CIB is packaged as a Docker container is the Node version (that needs to be at least 14). However, I just found out the current [Node version for GitHub-hosted runners is now 16](https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/).
So probably it's possible to drop the container packaging (although I'm not sure how this works with self-hosted runners).

**Comment by robvanderleek** [comment]
> Thank you for the quick reply! I will check out the link you gave. I assume that if the `issue-branch.yml` file does not exist, then it will continue on anyway?

Yes, normally, if the file does not exist, the next step is to look for the file in a different location ([user/org wide configuration](https://github.com/robvanderleek/create-issue-branch#organizationuser-wide-configuration)).
It's just one of the first calls, there will be more calls to the GitHub API after it.

**Comment by cignatow** [comment]
Unfortunately, creating a proxy configuration JSON for docker containers on the runner didn't seem to solve the issue. I will try to revisit this again in the future and see if I can get it to work. I appreciate all your help and the information you provided!

**Comment by robvanderleek** [comment]
Hi @cignatow 

FWIW, the runtime for the action has been moved back from Docker to Node: https://github.com/robvanderleek/create-issue-branch/pull/593

Thanks for your feedback & good luck,
Rob
