### ISSUE TITLE
Academic license

### ISSUE THREAD

**Issue by TobiasGoetz** [robvanderleek/create-issue-branch#598]
Hi,
I am a student studying computer science.

We are in the process of setting up an org and repositories for the projects me and my fellow students have to do.

I would really appreciate a educational license to use this app with my private repositories.

Thanks in advance,
Tobias

**Comment by robvanderleek** [comment]
Hi @TobiasGoetz 👋 

Private repositories in your personal GitHub account are included in the Free plan of this app 😄 

Let me know the name of the educational org you are setting up and I'll add that org to the Free Pro plan list, OK?

KR, Rob

**Comment by TobiasGoetz** [comment]
Hi @robvanderleek 

thanks for the response.

The org's name is "DHBW-FN"

Thanks a lot for the free pro plan. This will really come in handy managing issues, branches and overall development.

Best regards,
Tobias

**Comment by robvanderleek** [comment]
Hi @TobiasGoetz 

I've added DHBW-FN to the list of free Pro plan orgs.

Good luck with the project work!
Rob
