### ISSUE TITLE
Use a collapsable section for description copied to PR

### ISSUE THREAD

**Issue by arcsur** [robvanderleek/create-issue-branch#611]
Would it be possible to consider using a collapsible Markdown section for the issue description copied to PR option?

I like having the original info in there, but I tend to have to edit it and put at least a line break between the PR description and the original issue description.  As an example, imagine this issue was a PR and the below collapsible section was used

<details>
<summary><b>Original issue description</b></summary>
<blockquote>

This would be the original issue description that was copied into the PR.

* _Note that it is important to have the newline after the &lt;blockquote&gt; tag (or the last html tag before the copied MD description data), otherwise the contents won't be processed as markdown._
</blockquote>
</details>

closes #XXX

**Comment by robvanderleek** [comment]
Hi @arcsur 

Adding text/tags around the copied issue description is pretty easy ([this is the place in the code](https://github.com/robvanderleek/create-issue-branch/blob/4cd5a725a423675e1fab9e764173b8e09547861c/src/github.js#L283).)

I don't use the copy description feature a lot myself so not sure if users depend on it being copied verbatim to the PR body, and if that should stay the default (and this behaviour a configuration option).
Also, do you find the &lt;blockquote&gt; helpful? Or is it necessary for proper Markdown formatting?

**Comment by arcsur** [comment]
The blockquote in the example just helped to lay it out better when expanding so it looked like it is part of the expanded section.  It is not strictly necessary (but it does look better) so long as you have an extra new line after the prior html tag, the content will format as markdown.

Honestly, I find the original issue description useful to have in a PR but it gets messy editing the PR description after the fact.  I think the approach I am proposing is kind of the best of both worlds.  Not too sure how valuable it is just having it verbatim with no expanding section would be over the expanding section version.  Personally I don't see that it would matter for most usages and the folding section provides better presentation while maintaining the exact layout of the original issue.

**Comment by arcsur** [comment]
@robvanderleek Apologies for not responding for so long.  This looks exactly how I would want it.  Can this be merged into the main app?

**Comment by robvanderleek** [comment]
Hi @arcsur 

It's merged to main, thanks for proposing this feature :+1:

KR, Rob

**Comment by arcsur** [comment]
Thanks @robvanderleek
