### ISSUE TITLE
subsititution for PR name?

### ISSUE THREAD

**Issue by mikesongming** [robvanderleek/create-issue-branch#612]
can add a entrypoint for PR name customization as the [Substitution placeholders](https://github.com/robvanderleek/create-issue-branch#substitution-placeholders)?

**Comment by robvanderleek** [comment]
Hi @mikesongming 

Currently the title of the PR is the title of the issue for which it was openend.
Do I understand correctly you want to have another title for the PR than the issue title? And you want to be able to use substitution placeholders in that PR title?

Can you perhaps give an example of an issue title and the PR title you want for that issue?
