### ISSUE TITLE
Option for [skip ci] in pr message

### ISSUE THREAD

**Issue by flamisz** [robvanderleek/create-issue-branch#634]
Hi Rob,

do you think we can add an option in the config, to include the `[skip ci]` text in the empty commit message?

There is no point to run all the CI-related things on the draft PR and GitHub has this feature:

https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

If you want me to create a PR let me know.

Thanks
Zoltan

**Comment by robvanderleek** [comment]
Hey @flamisz 👋 

That sounds like a feature that I should have included as a default 😉 
The commit to open a (draft)PR is empty but the commit message currently [contains a standard text](https://github.com/robvanderleek/create-issue-branch/blob/455f5c0b48b45a3aae250cd4abf12dfd83f755e1/src/github.js#L271).
We can add an option to the config (`prSkipCI`?) that, when enabled, appends `[skip ci]` to the standard text?

Let me know if this would work for you. I think this is a nice feature to get started working on the codebase but I can also look at it the coming days.

KR, Rob

**Comment by flamisz** [comment]
yes, that sounds just like I imagined 🙂

**Comment by robvanderleek** [comment]
Hi @flamisz 

This feature is live, [the documentation is here](https://github.com/robvanderleek/create-issue-branch#skip-ci-workflows).

I've tested it in the [staging environment](https://github.com/facio-ergo-sum/test-repo-create-issue-branch-staging-app/issues/24), let me know if you bump into any issues 🙂 

Thanks for bringing this feature up!

**Comment by flamisz** [comment]
thanks again for your quick response and job 👍
