### ISSUE TITLE
Using create-issue-branch for a project

### ISSUE THREAD

**Issue by Arthur-Devs** [robvanderleek/create-issue-branch#642]
Hello, 

I contact you because i use your project for a school project ( second year of a master's degree).
This project is to create a website for a Non-profit organization. 
I would like to know if it's possible to use your project without paid ?

Thanks You Arthur

**Comment by robvanderleek** [comment]
Hi @Arthur-Devs 

Yes, there's a Free Pro Plan for non-profits 🙂 

Do you have a GitHub organization name that I can add to the list of free pro plans?

KR, Rob

**Comment by Arthur-Devs** [comment]
Hi @robvanderleek ,

This is the link of github organization [here](https://github.com/lecoindesdevs).
I also add a link to a document about the non profit organization. 

[JOAFE_PDF_Unitaire_20220023_01797.pdf](https://github.com/robvanderleek/create-issue-branch/files/9556513/JOAFE_PDF_Unitaire_20220023_01797.pdf)

Thanks you and have a good day
Arthur

**Comment by robvanderleek** [comment]
I've added `lecoindesdevs` to the list of free pro plan users.

All the best with your organization!
Rob

**Comment by Arthur-Devs** [comment]
Thanks you 

Have a good day 
Arthur
