### ISSUE TITLE
Auto close issue not working

### ISSUE THREAD

**Issue by joaocatalao** [robvanderleek/create-issue-branch#690]
I made a workflow using this action, but for some reason the auto-close issue configuration is not working.
It's required that the issue number is included in the branch name, and in my workflow it is.

My branch name is set as:
- branchName: 'issue-${issue.number}/${issue.title,}'

And also I have the auto-close:
- autoCloseIssue: true

So, what's going wrong?

**Comment by robvanderleek** [comment]
Hi @joaocatalao 

Sorry to hear create-issue-branch did not work as expected.
I tried your branch name pattern and found out there was indeed a 🐛 in the code that extracts the issue number.
The good news is that the fix was relatively easy, can you please try again?

KR, Rob
