### ISSUE TITLE
Open PR's without creating a branch

### ISSUE THREAD

**Issue by joaocatalao** [robvanderleek/create-issue-branch#695]
Hey again! Thanks for the fix on the auto-close issue.

I have another question/feature request.

Is it possible to open a PR without creating a new branch based on the labels?

For example, I have master and develop. Whenever there's a "release" label on the new issue, instead of creating a branch based on develop and going into master, I wanted to open a PR directly from develop to master. Is that possible right now? Or if not what do you think about that feature?

**Comment by robvanderleek** [comment]
Hi @joaocatalao 

The app will always try to create a branch based on the issue label.
I think I understand your use case but that logic seems a bit stretched for this app: for certain issue labels open a PR for a certain branch to the default branch.
Maybe there are other apps/actions that support this kind of issue automation?
