### ISSUE TITLE
Create branch automatically on private repo

### ISSUE THREAD

**Issue by megasteve19** [robvanderleek/create-issue-branch#701]
Yes! I know It's silly. Currently repo is total empty and private. But eventually it will be going to public. I wanted to leverage `projects` to manage project before going public. Is there a way to do that? If not, appreciate it.

**Comment by robvanderleek** [comment]
Hi @megasteve19 👋 

Not sure I understand your question. This App/Action can work on private repos, even if they are empty. It's free for personal private repos and you'll need [a Pro plan](https://github.com/marketplace/create-issue-branch/) for organizational private repos.

**Comment by megasteve19** [comment]
I'm so sorry, I guess I was sleepy when opening this issue. I have an organization and I installed this app into it. The problem is there's nothing in it. Just a two empty private repo. But these repo's will be public when they ready. I was asking that is it possible to use it or it's strictly limited to private repo's. Thank you for your time :)

**Comment by robvanderleek** [comment]
No problem! 😄 
KR, Rob
