### ISSUE TITLE
Fixed number of digits for issue.number

### ISSUE THREAD

**Issue by josep-llodra** [robvanderleek/create-issue-branch#712]
Considering that: 

`branchName: '${issue.number}-${issue.title}'`

this would create a branch like "3-My_issue_title".

Would it be possible to introduce some number format notation for adding left pad with 0 if necessary:

e.g.: `branchName: '${issue.number|4}-${issue.title}'`

this would lead to a branch like "0003-My_issue_title".

This enables alpha numeric sorting of issues.

Thank you

**Comment by robvanderleek** [comment]
Hi @josep-llodra 

I've added a "left-padding with zeros" operator, please [see the Readme](https://github.com/robvanderleek/create-issue-branch#left-padding-with-zeros).

Let me know if you bump into any issues.

KR, Rob
