### ISSUE TITLE
create issue

### ISSUE THREAD

**Issue by sridharatreya** [robvanderleek/create-issue-branch#717]
we are a startup.  we are not in production or not in revenue mode yet

**Comment by robvanderleek** [comment]
Hi @sridharatreya 

The free plan is intended for non-profit organizations but I can give a 2-month free trial, would that help? What is the name of your GH organization?

KR, Rob

**Comment by sridharatreya** [comment]
Thanks. Name of GH org is Atreyalabs Inc.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by robvanderleek** [comment]
Is this the org? https://github.com/atreyalabs-ai
