### ISSUE TITLE
Add a link to the issue when creating a pull request

### ISSUE THREAD

**Issue by josep-llodra** [robvanderleek/create-issue-branch#733]
Hello Rob,

For us is a bit inconvenient that we cannot go easily from a PR to the Issue whose branch originated this PR.

Maybe the `create-issue-branch` action could add a comment to the PR when it is created (if cib can detect that there is a linked issue, parsing the branch name, as it does now I guess), the comment could be something like:

> Pull request linked with Issue #123 (and #123 being an hyperlink to the issue itself)

Do you think this is feasible?

PS: We have seen that using the build-it github create branch method, the PR is linked with the issue and there is a link. But not using cib.

**Comment by robvanderleek** [comment]
Hi @josep-llodra 

My time is currently limited to look into this but CIB should put a `closes #123` comment in the PR.
I've just verified that [in this repo](https://github.com/facio-ergo-sum/test-repo-create-issue-branch-prod-app/pull/28) (using the App, not the Action).
For this to work the `issue-branch.yml` configuration file only need to contain `openPR: true`

AFAIK GitHub does not provide an API endpoint to link PRs with Issues explicitly (at least not the last time I looked). Connecting both through comments is the only option for an App/Action.

What version of the action are you using in your workflow? (`@main` should be fine).
Can you also send me your `issue-branch.yml` contents?

**Comment by robvanderleek** [comment]
Hi @josep-llodra 

The `openPR: true` option does open a new PR (or draft PR with `openDraftPR: true`) every time a branch is created, I'm not sure if that fits your workflow, let me know 🙂 

[Conventional PR titles](https://github.com/robvanderleek/create-issue-branch#conventional-pull-request-titles) is a new feature I'm working on. Based on labels it automatically inserts a [conventional commits](https://www.conventionalcommits.org/) style prefix in the title of the pull-request. This makes the Git history easier to read and can also be used for [semantic versioning](https://semver.org/).

Let me know if you want to try out this new feature, I'm interested in positive/negative feedback. This feature should work well in combination with the `openPR: true` option (or any other option).

KR, Rob
