### ISSUE TITLE
Update the same branch if the issue is re-assigned

### ISSUE THREAD

**Issue by gaiborjosue** [robvanderleek/create-issue-branch#754]
Hello,

I am having a bit of trouble trying to make this scenario work:

1. The user submits an issue.
2. My action gets triggered.
3. Suppose the action fails, but the issue's branch is still created.
4. The user fixes the error in the issue and reassignes themselves to the issue so the action re-runs.
5. However, when the action reruns, even if it is the same issue, instead of updating the same branch, it updates main/master. What I mean by this is that the output variable of creating a new branch ("branchName") is empty. Therefore, instead of updating the existing branch, my workflow updates the main because the branch name received was empty.

I have to create new issues every time I want to update something in the issue's branch.

Thanks,
Edward

**Comment by robvanderleek** [comment]
Hi @gaiborjosue 👋 

Thanks for the detailed issue, helped a lot.

The output variable is now always set, even if the branch already exists ([PR](https://github.com/robvanderleek/create-issue-branch/pull/755)).

Hopefully, this works for your use case, if not, let me know.

KR, Rob

**Comment by gaiborjosue** [comment]
Hello @robvanderleek, first of all, I want to thank you for being available and open to help with my issue. Your commitment to this project is really appreciated by me.

I am going to test the changes and let you know. Awesome tool!
