### ISSUE TITLE
Some times opening a PR fails

### ISSUE THREAD

**Issue by josep-llodra** [robvanderleek/create-issue-branch#757]
The error message looks like this and it is written as a comment in the issue by the bot:

```Could not create PR (Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between development and enhancement/0305-xxxx"})```

Steps are these:

1. Issue is created
2. Issue is assigned
3. Branch is created by the bot (a message appears in form of comment) in the issue
4. That error appears in form of comment in the issue
5. No PR is created

This error does not happen all the time, just from time to time.
Is it some sort of race condition? Any other user have experienced this?

Thank you

**Comment by robvanderleek** [comment]
Hi @josep-llodra 

Thanks for reporting, I'm sorry to hear the app is not working as it should.

This indeed seems to be an unhappy path that is triggered only sometimes.
I've setup [a basic test in this repo](https://github.com/facio-ergo-sum/test-repo-create-issue-branch-prod-app/issues/31) and tried it 3 times in a row but all times it succeeded.

Are there more details about your configuration that you can share? For example, the contents of your `issue-branch.yml`.

I haven't received reports of other users about this issue so far.

KR, Rob

**Comment by patch0** [comment]
I've also seen this too

**Comment by robvanderleek** [comment]
Hi @josep-llodra, @patch0 

I've dug deeper into the Sentry logs and the behavior you're observing might have to do with the issue being locked. 
What I see in the logs is: `HttpError: Unable to create comment because issue is locked.`, do you also see this message in the comment?

If it is caused by the issue being locked for create-issue-branch, do you perhaps have other integrations running after an issue is assigned?

**Comment by robvanderleek** [comment]
@patch0 Can you perhaps link to some issues that were not handled correctly, so I can take a look? 🙂

**Comment by patch0** [comment]
> @patch0 Can you perhaps link to some issues that were not handled correctly, so I can take a look? 🙂

Sorry, I saw this comment last week, but I think it must be a temporary GH issue.  We don't lock issues, so I don't think it was that.  I've not seen it since, so maybe we're good?

Thanks!

**Comment by robvanderleek** [comment]
I'm keeping a closer eye on the logs and also made the code a bit more robust.
Let's hope this 🐛 will not return. If not, please re-open this issue 🙂 

Rob
