### ISSUE TITLE
Handle all other conventional types as pr prefixes

### ISSUE THREAD

**Issue by Nonudian** [robvanderleek/create-issue-branch#759]
Hello,

I would like to know if something like making available all other conventional types, such as `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, and `test:` (or even owned custom types), as pull request prefixes, could be planned in the future.

I've checked the `getConventionalPrTitlePrefix` implementation, and it only handles `fix:` and `feat:` prefixes, which is a bit annoying when I want pushing some granularity in my pull request titles.

Do you think it could be achievable ? Thanks !

**Comment by robvanderleek** [comment]
Hi @Nonudian 👋 

Yes, this is achievable, I'll look into it 🙂 

Regarding conventional PR titles: this is still a feature under development and I'm really interested for what use cases users are using it (e.g.: getting a nicer git log/semantic versioning/other). If you could provide some feedback that would be great.

KR, Rob

**Comment by robvanderleek** [comment]
Hi @Nonudian 

I've added default support for the missing types, and also extended the configuration to add new ones. Please see the [README](https://github.com/robvanderleek/create-issue-branch#configuring-semantic-versioning-semver-style).

Let me know if you bump into any issues.

**Comment by Nonudian** [comment]
Hello @robvanderleek,

Sorry for the delay, and thanks for your work, I will check that as soon as possible. 

About feedback, our main use case today is prioritizing tasks, using conventional labels (as we are a little team, we want to stay simple). All you're made is sufficient for us, so I don't have any ideas for the moment.
