### ISSUE TITLE
Automatically delete branches when issues are closed

### ISSUE THREAD

**Issue by CycleBai** [robvanderleek/create-issue-branch#880]
First of all, thank you for creating this app! It's very helpful for tracking.

I created an Issue after installing it for testing purposes, and it created a branch just fine, but when I closed the issue, the branch wasn't deleted.

I looked in the README file and there doesn't seem to be a setting option for this.

Is it possible to implement it? If it's not planned, please let me know, thanks!

**Comment by robvanderleek** [comment]
Hi @CycleBai 

Good to hear you're enjoying my app 😄 

I use the GitHub feature ["Automatically delete head branches"](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches) myself (you can find it under repository Settings > General > Pull Requests).

Does this work for your use-case? Or would you still like to have this feature in Create Issue Branch?

KR, Rob

**Comment by CycleBai** [comment]
Thanks for your reply.

My application scenario does not associate issues with pull requests, so it does not seem to work.

Is it possible to solve this in other ways?

**Comment by robvanderleek** [comment]
Ah, interesting, can you describe your workflow in general?

Would you like CIB to *always* delete the branch when the associated issue is closed, or only conditionally (e.g. when the branch is equal to (has been merged into) another branch)?

**Comment by CycleBai** [comment]
Thank you for your reply.

I usually create an Issue branch after the developer confirms the Issue to back up the problem scenario to avoid the environment being overwritten by later code.

I hope to set it up in the yml file in a way similar to the following:

```

del-branch: issue-closed
```

Something like this may be more flexible?

**Comment by robvanderleek** [comment]
Hi @CycleBai 

I've implemented a fairly straightforward option to automatically delete a branch when a related issue is closed.
Please [see the documentation for more information](https://github.com/robvanderleek/create-issue-branch?tab=readme-ov-file#automatically-delete-issue-branch-after-closing-an-issue).

Let me know if this works for your use-case.

KR, Rob

**Comment by CycleBai** [comment]
Thanks, that's exactly what I wanted.
