### ISSUE TITLE
Issue word replacement

### ISSUE THREAD

**Issue by bitsbybrad** [robvanderleek/create-issue-branch#97]
## Use Case:

I would prefer granularity on the word issue.
Typical workflow we use is something like jira -> bitbucket.  

For example:
* User has project a) Cool Cats and project b) Dope Dogs
* They develop under a codename for the project, usually two to three letters at most.
* They use. CC-{ISSUE_NUMBER} and DD-{ISSUE_NUMBER} to refer to their issues internally, these issues may cross pollinate repos and project so search is key.

I've added a new key to the config: `issueReplacement :: String`
If issueReplacement is present it:
- disregards `branchName: tiny`
- prepends it's value to the rest of the string pre /

`stringReplacement: foo`  => `foo-{num}-{title}`
`stringReplacement:bar && branchName: short` => `bar-{num}`

please feel to critique anything in the pr.

**Comment by robvanderleek** [comment]
Hey @bitsbybrad 😄 

Thanks for the clear description and PR!
Like your code changes, concise and with unit-tests 👍 

I've been thinking before about a similar functionality that I would like your feedback on:
Currently `branchName` can have the values `{tiny,short,full}`. I want to add the option to give `branchName` a custom string with `${...}` placeholders that are substituted with fields from the GitHub webhook JSON object.

For example, your first branch naming scheme would then be configured like:
```yaml
branchName: 'foo-${issue.number}-${issue.title}`
```
and your second naming scheme would be configured like:
```yaml
branchName: 'bar-${issue.number}'
```

The functionality to do the replacement is already implemented for the branch name prefix based on issue label functionality. This solution prevents a separate `issueReplacement` configuration parameter and gives users even more flexibility in the naming scheme. A slight drawback is adding an option to the `branchName` parameter that has a different "type" than the other 3 parameters but I don't see major problems there.

What do you think?

**Comment by bitsbybrad** [comment]
Thanks for the compliment and your speedy reply!

> The functionality to do the replacement is already implemented for the branch name prefix based on issue label functionality.

I must have missed this, and looking back now I'm not sure I see where you're talking about.

For clarity, when you say `prefix based on issue label functionality` are you referring to this?

```yaml
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
```
 
If so, yeah I'm totally on board with that.

It would look something like this?

```yaml
branchName:
  - format: short
    prefix: foo
```
yields `foo-${issue.number}`

**Comment by robvanderleek** [comment]
Sorry for the confusion: I meant there's functionality in the code to do the replacement 😄 

The [`interpolate`](https://github.com/robvanderleek/create-issue-branch/blob/d207f641f561b7c73fe02894f4c98be65a22b6d6/probot.js#L238) function takes a string (for example `foo-${issue.number}`) and replaces `${...}` occurrences with field values of the object given as a second argument.

So, I propose to keep the configuration like:
```yaml
branchName: 'foo-${issue.number}`
```
and in the [`getBranchNameFromIssue`](https://github.com/robvanderleek/create-issue-branch/blob/d207f641f561b7c73fe02894f4c98be65a22b6d6/probot.js#L189) first check if `branchName` is set (if not return the default). If it is set, check for `tiny`, `short` or  `full` and if those do no match call  the `interpolate` function on the configuration string.

Do you want to pick this up in your PR? I think your existing unit-tests only require a tiny modification (give a YAML configuration with the `branchName` parameter) and the code also needs a small amount of changes.

Let me know if your need help.
Two more remarks about the PR:
1. Can you remove the coverage reports? It's fine to add `coverage` to `.gitignore`
2. Can you make a start with updating the documentation in `README.md`?

Thanks for your help!

**Comment by robvanderleek** [comment]
Hey @bitsbybrad 😄 
Do you need any help?
Hope you are well.
Best, Rob

**Comment by bitsbybrad** [comment]
Rob,
I should have time this weekend to work on this. Things have been crazy due to corona and I havn't had time for open source! Will try to have some meaningful progress this weekend.

Stay safe!
Brad

**Comment by robvanderleek** [comment]
Hi Brad,

Don't feel any obligation to work on this issue soon! Your safety and well being are most important now.

Only do open source if you want some distraction 😄 

Take care, Rob

**Comment by robvanderleek** [comment]
Hey @bitsbybrad 

Hope you are safe and healthy.

Wanted to let you know an issue came up (#125) that I could solve with the logic discussed in this issue. So, now it's possible to define custom branch name patterns, such that:
```yaml
branchName: 'foo-${issue.number}'
```
configures the app to create branches that have names like `foo-125`

I used all of your test code in the PR (thanks a lot for that!). You can see how the application logic looks in this commit: https://github.com/robvanderleek/create-issue-branch/commit/57bc03435e4adb4adfc5655243c3b612e3aaf74c

Tnanks for all your efforts, if you're OK with the current behaviour I'm going to close this issue.
